---
- name: MFGI_UAT_DB_IDFGICU_CHECK_GAP_REP_DEV
  hosts: "{{ standby_db_IDFGICU1 }}"
  gather_facts: no
  tasks:
    - name: Load environment Oracle
      shell: ". .IDFGICU1"
      args:
        executable: /bin/bash

    - name: Jalankan query perbandingan log archive dan log history
      shell: |
        sqlplus -s / as sysdba <<EOF
        SET LINESIZE 200
        SET PAGESIZE 100
        SET FEEDBACK OFF
        SET HEADING ON
        SELECT ARCH.THREAD# "Thread",
               ARCH.SEQUENCE# "Last Sequence Received",
               APPL.SEQUENCE# "Last Sequence Applied",
               (ARCH.SEQUENCE# - APPL.SEQUENCE#) "Difference"
        FROM
          (SELECT THREAD# ,SEQUENCE#
           FROM V$ARCHIVED_LOG
           WHERE (THREAD#,FIRST_TIME ) IN
             (SELECT THREAD#,MAX(FIRST_TIME)
              FROM V$ARCHIVED_LOG
              GROUP BY THREAD#)) ARCH,
          (SELECT THREAD# ,SEQUENCE#
           FROM V$LOG_HISTORY
           WHERE (THREAD#,FIRST_TIME ) IN
             (SELECT THREAD#,MAX(FIRST_TIME)
              FROM V$LOG_HISTORY
              GROUP BY THREAD#)) APPL
        WHERE ARCH.THREAD# = APPL.THREAD#;
        exit;
        EOF
      args:
        executable: /bin/bash
      register: log_comparison_result

    - name: Tampilkan hasil query perbandingan log
      debug:
        var: log_comparison_result.stdout